# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c741680a88f249ae0e05b93e3c47e4252e0141117d5d38972dfe49826b352cab1fb9dcb3c3ddd347298d0108901a4f49a55b9e61387efd63823280b8d665880a

test:
  secret_key_base: b5684c70ee1327ed5910f8df8c65f0acfdeef444f26831657e39309b5b527cded9f8c46790bd45855f367db09f964ba85f0b56fdab1768f7752b1462f5bffd43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
